# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6db87523fc027156d0884153fc30e1b13e12e7e6e03c486117ba68351b47296624b368e7a2b09cab62d423f68becf0d1974c7f755d29b38bbc41393cea436a24

test:
  secret_key_base: 48276b8cad49ad957f54f074f3b138c9f37c0e2e7e84698dfdea372f6145d483719a3d7d6c7a5a146dfd27acd9139479687105a41924b5bb411ed4b0338bb3de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
